### PR TITLE
[Venues] Add support for venues checks

### PR DESCRIPTION
**Pull request by davidakachaos**
So this adds support for checking venues. 
It checks venues according to some rules in a similar way the segments are checked. There is a lot of commits in this PR, but when we merge this, these can be squatted in one commit.
I have merged my local venue branch into a local master branch and fixed the merge issues there, than I've opened this PR so the merges can be handled by the Github system.

### CODE REVIEW

**Comment by davidakachaos** [comment]
@berestovskyy I think if we merge this I can move the checks out in a plugin? Maybe in that way we can make some progress with #75 too. This will mean after merging I'll rip out the venue checks and move them to a separate plugin if able. What do you think?

**Comment by berestovskyy** [comment]
Hey David,
Thanks for the contribution. How was the branch tested?

**Comment by davidakachaos** [comment]
Hey :smile: 
Sorry for getting back this late; I've tested it mostly myself. Mostly by using it during a MapRaid in the Netherlands, haven't had much feedback from others unfortunately.

Is there a way to disable checking venues by default? I see the setting in src/basic.js (function resetDefaults) but I don't know how to disable it by default after a user upgrades to the new version. I think that if we disable the venue checks by default, so people can opt-in to see for them selves if it works correctly for them?

**Comment by berestovskyy** [comment]
> I think that if we disable the venue checks by default, so people can opt-in to see for them selves if it works correctly for them?

We touch a lot of segment's functionality, so the change should be properly tested even if we make the venues disabled by default.

The `resetDefaults()` is the way to init the settings. On login, Validator reads stored settings and overrides the defaults. So if the setting is new, it will not be overridden.

There is also an option to ignore stored settings, i.e. reset all the settings to their defaults. We can achieve that by changing (increasing) the `AS_PASSWORD`. But I'm pretty sure in this situation we don't need that.

**Comment by berestovskyy** [comment]
I'll try to test the branch, but it would be better to have a few people on this...

**Comment by berestovskyy** [comment]
Are you ready to solve issues if any David? ;)

What would be the best date for you to publish this change?

**Comment by davidakachaos** [comment]
It seems I need to update the I18n first, but I think that shouldn't be a large problem (I hope)
I'll need to move the changes in release.js up to the newest :wink:
This week should be fine I think; I will look into the I18n repo first to make sure it's updated.

**Comment by davidakachaos** [comment]
:shipit: Here it goes.

**Pull request merged**
