### PR TITLE
[WIP] Initial plugin support

### PR DESCRIPTION
**Pull request by davidakachaos**
Not finished, not polished, but working.
This is just to show how it could work. Open for discussions and ideas 😃

### CODE REVIEW

**Comment by berestovskyy** [comment]
Thanks, David, very good concept. IMO there are few general issues to solve:

1. Performance. The interface between Validator and plugins should be fast enough. We should assume the plugins might refer external databases, make HTTP requests etc. Performance should nod degrade even with "slow" plugins.

Also, remember those check groups inside Validator? If a segment is not drivable, we do not run a whole bunch of checks. The same concept should be implemented here.


2. Compilation. I guess compiled version of Validator does not have `segment.report()` etc. There should be explicitly defined API sustainable to compilation process.


3. Unique IDs. There are potential issues with IDs, like one plugin (mistakenly) reports issue X, while it is not even belong to this plugin. One of the solutions could be to assign (or to prefix) IDs automatically by Validator.


Overall, I think we need to design the interface between Validator and plugins very well, this is the most important part of #58.

**Comment by davidakachaos** [comment]
I agree we should design this carefully and good so we provide a nice plugin interface to other programmers.
- Perfomance: Like I said in #74 we could consider a async interface between the main script and plugins to ensure a bit of performance. We fire a function for each plugin and wait for the results. What plugins check and don't check, we don't really care about. We give them the option to check segments we provide (excluding ones we filter like already seen or outside of an city) and the venues we provide likewise. So the filters in our interface still apply to the segments/venues we pass to the plugins.

- Compilation. As far as I can see the `segment.report()` funtion gets complied to `a.report()` or similar. I used the complied version when I tested the plugin function and the `report` function still worked. I passed the entire `segment` object to the plugin and its functions were also passed. These were not compiled to strange names. As far as I can see the compiler does rename inline functions, but functions on objects it leaves alone (thankfully) I think we can use the report function in the plugin without issues.

- Unique IDs. Yes 😉 We should prefix plugin issues so we can see what is a "core issue" and what is a "plugin issue" when reporting. This will prevent plugin issues from overwriting core issues. 

- Currently there is a maximum hard-coded number of checks. This should change with the introduction of plugins. There is not really a way to tell the total number of checks pre load of the plugins. I don't know how to change this yet, we will figure it out.

**Comment by davidakachaos** [comment]
About the unique IDs; couldn't we just enforce plugin authors to use other ids than we use? Refuse loading the plugin when they don't?

**Comment by berestovskyy** [comment]
> We give them the option to check segments we provide (excluding ones we filter like already seen or outside of an city) and the venues we provide likewise.

1. We need no fire a function if the plugin does not expect drivable segments, for example.
2. We need to consider that some plugins might need nearby or other segments to check.

> So the filters in our interface still apply to the segments/venues we pass to the plugins.

Yeah, there should be an interface so the plugin can communicate what kind of segments it expects. Or we can use an event model, so plugins can subscribe for a "drivable segment" event, for example.

> Compilation. As far as I can see the segment.report() funtion gets complied to a.report() or similar.

Ok, great!

> Currently there is a maximum hard-coded number of checks.
> couldn't we just enforce plugin authors to use other ids than we use? Refuse loading the plugin when they don't?

Yes we can enforce plugins to use only their IDs. This will solve the issue with number of checks as well. The downside, this requires some planning from our side, which would be better to avoid.

On the other hand, we can assign a 100 IDs for each plugin and auto-assign a prefix, based on the plugin name, for example.

**Comment by berestovskyy** [comment]
Sorry, I don't have much time at the moment to look into this. Once the plugins are done, do we need to highlight the issues?

Just an idea. We might add a long loop inside a test check to emulate a "hard work" and run few of those checks to see how it goes...

**Comment by davidakachaos** [comment]
It's okay, I didn't look in to this for a bit either. Yes the issues must be highlighted, but because we use the ```.report(X)``` function these will already be added for highlighting (as far as I know)

We can create a simple plugin that stalls check by some time per segment and see how that performs. Of course it will slow things down (I think, pre-test) but I wonder if we can make Validator detect things like that and report to the user what plugin in causing a significant slow down.

**Pull request closed without merging**
